/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// Import environment variables securely
export const projectId = import.meta.env.VITE_SUPABASE_PROJECT_ID || '';
export const publicAnonKey = import.meta.env.SUPABASE_ANON_KEY || '';

// Validation function to check if credentials are properly configured
export const validateCredentials = (): boolean => {
  return !!(projectId && publicAnonKey);
};
